name: M3U8_ACTION

on:
  workflow_dispatch:
  # Run 4 Hours after https://https://github.com/ericziethen/ez-iptvcat-scraper
  # This should be just after midnight in Australia
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
    - master
    - main

jobs:

  m3u8_action:
    name: m3u8_action
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo $(date) >> last_attempt.txt

          cat last_attempt.txt
          ls -ltr
          git status
          git add last_attempt.txt
          git status
          git commit -m "cron: setting last attempt time stamp" -a
          git status
          git push

      ### SETUP THE ENVIRONMENT
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Setup Environment
        # e.g. create work dirst, store in env variables ... https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions
        run: |
          echo "IPTVCAT_DATE=$(date -d "13:00" '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "IPTVCAT_DATE_YESTERDAY=$(date -d "yesterday 13:00" '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "IPTVCAT_DOWNLOAD_DIR=${{ github.workspace }}/temp/iptvcat" >> $GITHUB_ENV
          echo "M3U8_DIR=${{ github.workspace }}/temp/m3u8" >> $GITHUB_ENV
          echo "EPG_TEMP_DIR=${{ github.workspace }}/temp/epg" >> $GITHUB_ENV
          echo "M3U8_STATIC_DIR=${{ github.workspace }}/temp/m3u8_static" >> $GITHUB_ENV

          # Update pythonpath used for our scripts
          echo "PYTHONPATH=$PYTHONPATH:${{ github.workspace }}" >> $GITHUB_ENV

      - name: Setup Dirs
        run: |
          echo "IPTVCAT_DATE: '${IPTVCAT_DATE}'"
          echo "IPTVCAT_DATE_YESTERDAY: '${IPTVCAT_DATE_YESTERDAY}'"
          echo "IPTVCAT_DOWNLOAD_DIR: '${IPTVCAT_DOWNLOAD_DIR}'"
          echo "M3U8_DIR: '${M3U8_DIR}'"
          echo "EPG_TEMP_DIR: '${EPG_TEMP_DIR}'"
          echo "M3U8_STATIC_DIR: '${M3U8_STATIC_DIR}'"

          echo "Command: 'mkdir -p ${IPTVCAT_DOWNLOAD_DIR}'"
          mkdir -p ${IPTVCAT_DOWNLOAD_DIR}
          echo "Command: 'mkdir -p ${M3U8_DIR}'"
          mkdir -p ${M3U8_DIR}
          echo "Command: 'mkdir -p ${EPG_TEMP_DIR}'"
          mkdir -p ${EPG_TEMP_DIR}
          echo "Command: 'mkdir -p ${M3U8_STATIC_DIR}'"
          mkdir -p ${M3U8_STATIC_DIR}

          echo "Command: 'ls -alt ${IPTVCAT_DOWNLOAD_DIR}'"
          ls -alt ${IPTVCAT_DOWNLOAD_DIR}
          echo "Command: 'ls -alt ${M3U8_DIR}'"
          ls -alt ${M3U8_DIR}
          echo "Command: 'ls -alt ${EPG_TEMP_DIR}'"
          ls -alt ${EPG_TEMP_DIR}
          echo "Command: 'ls -alt ${M3U8_STATIC_DIR}'"
          ls -alt ${M3U8_STATIC_DIR}

      ### DOWNLOAD REQUIRED DATA ###
      - name: Get IPTVCat Release
        run: |
          echo "Command: './scripts/iptvcat/get_iptvcat_scraper_release.sh "${IPTVCAT_DOWNLOAD_DIR}" "${IPTVCAT_DATE}" "${IPTVCAT_DATE_YESTERDAY}"'"
          ./scripts/iptvcat/get_iptvcat_scraper_release.sh "${IPTVCAT_DOWNLOAD_DIR}" "${IPTVCAT_DATE}" "${IPTVCAT_DATE_YESTERDAY}"

      - name: Get EPG from M3U4U
        run: |
          echo "Command: './scripts/download_file_allow_failiure.sh "${{ secrets.M3U4U_EPG_URL_XML_GZ }}" "${EPG_TEMP_DIR}" "${{ secrets.M3U4U_EPG_FILE_NAME_XML_GZ }}"'"
          ./scripts/download_file_allow_failiure.sh "${{ secrets.M3U4U_EPG_URL_XML_GZ }}" "${EPG_TEMP_DIR}" "${{ secrets.M3U4U_EPG_FILE_NAME_XML_GZ }}"

      - name: Get Static Files from Dropbox
        run: |
          echo "Command: './scripts/download_file_allow_failiure.sh "${{ secrets.DROPBOX_STATIC_M3U8_INDONESIA }}" "${M3U8_STATIC_DIR}" "indonesia.m3u8"'"
          ./scripts/download_file_allow_failiure.sh "${{ secrets.DROPBOX_STATIC_M3U8_INDONESIA }}" "${M3U8_STATIC_DIR}" "indonesia.m3u8"

          ls -alt "${M3U8_STATIC_DIR}"

      ### PROCESS THE DATA ###
      - name: Convert IPTVCat (JSON to m3u8)
        run: |
          echo "Command: 'ls -alt ${IPTVCAT_DOWNLOAD_DIR}'"
          ls -alt ${IPTVCAT_DOWNLOAD_DIR}
          echo "Command: 'ls -alt ${M3U8_DIR}'"
          ls -alt ${M3U8_DIR}

          echo "Command: 'python ./scripts/iptvcat/convert_iptvcat_scraper_files.py "${IPTVCAT_DOWNLOAD_DIR}" "${M3U8_DIR}"'"
          python ./scripts/iptvcat/convert_iptvcat_scraper_files.py "${IPTVCAT_DOWNLOAD_DIR}" "${M3U8_DIR}"

          echo "Command: 'ls -alt ${IPTVCAT_DOWNLOAD_DIR}'"
          ls -alt ${IPTVCAT_DOWNLOAD_DIR}
          echo "Command: 'ls -alt ${M3U8_DIR}'"
          ls -alt ${M3U8_DIR}

      - name: Merge with Static Files
        run: |
          ls -alt ${M3U8_DIR}
          ls -alt ${M3U8_STATIC_DIR}

          echo "Command: './scripts/merge_m3u8_files_in_dirs.sh "${M3U8_DIR}" "${M3U8_STATIC_DIR}"'"
          ./scripts/merge_m3u8_files_in_dirs.sh "${M3U8_DIR}" "${M3U8_STATIC_DIR}"

          ls -alt ${M3U8_DIR}
          ls -alt ${M3U8_STATIC_DIR}

      - name: Add Channel Categories
        run: |
          echo "Command: 'python ./scripts/import_categories_into_m3u8.py --category_file "./ez_m3u8_creator/categories/main.json" --m3u8_in_dir "${M3U8_DIR}" --m3u8_out_dir "${M3U8_DIR}"'"
          python ./scripts/import_categories_into_m3u8.py --category_file "./ez_m3u8_creator/categories/main.json" --m3u8_in_dir "${M3U8_DIR}" --m3u8_out_dir "${M3U8_DIR}"

      - name: Match EPG IDs
        run: |
          echo "Command: './scripts/match_epgid_to_names.sh "${M3U8_DIR}" "${M3U8_DIR}"'"
          ./scripts/match_epgid_to_names.sh "${M3U8_DIR}" "${M3U8_DIR}"

      - name: Add EPG URL to files
        run: |
          echo "Command: 'python ./scripts/add_epg_url_into_m3u8.py --epg_url "${{ secrets.DROPBOX_EPG_URL_XML_GZ }}" --m3u8_in_dir "${M3U8_DIR}" --m3u8_out_dir "${M3U8_DIR}"'"
          python ./scripts/add_epg_url_into_m3u8.py --epg_url "${{ secrets.DROPBOX_EPG_URL_XML_GZ }}" --m3u8_in_dir "${M3U8_DIR}" --m3u8_out_dir "${M3U8_DIR}"

      ### FILE UPLOADS ###
      - name: Upload EPG to dropbox
        run: |
          echo "Command: './scripts/upload_to_dropbox.sh "${EPG_TEMP_DIR}" "EPG" "********"'"
          ./scripts/upload_to_dropbox.sh "${EPG_TEMP_DIR}" "EPG" "${{ secrets.DROPBOX_UPLOAD_TOKEN }}"

      - name: Upload m3u8 files to Dropbox
        run: |
          echo "Command: './scripts/upload_to_dropbox.sh "${M3U8_DIR}" "IPTV" "********"'"
          ./scripts/upload_to_dropbox.sh "${M3U8_DIR}" "IPTV" "${{ secrets.DROPBOX_UPLOAD_TOKEN }}"
